version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: url-phase1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: urlshortener
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: urlshortener_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
